/**
 * USDA FoodData Central — SR Legacy nutritional data per 100g.
 * Source: https://fdc.nal.usda.gov/
 *
 * Each entry keyed by ingredient ID from recipe JSON.
 * All nutrient values are per 100g of the ingredient.
 */

export interface NutrientsPer100g {
  fdcId: number
  description: string
  calories: number       // kcal
  protein: number        // g
  totalFat: number       // g
  saturatedFat: number   // g
  carbohydrates: number  // g
  sugar: number          // g
  fiber: number          // g
  sodium: number         // mg
}

/** Weight conversion for unit: "whole" ingredients */
export const WHOLE_UNIT_GRAMS: Record<string, number> = {
  eggs: 50, // 1 large egg without shell ≈ 50g
}

export const USDA_NUTRIENTS: Record<string, NutrientsPer100g> = {
  butter: {
    fdcId: 173430,
    description: 'Butter, without salt',
    calories: 717,
    protein: 0.85,
    totalFat: 81.11,
    saturatedFat: 51.37,
    carbohydrates: 0.06,
    sugar: 0.06,
    fiber: 0,
    sodium: 11,
  },
  flour: {
    fdcId: 168894,
    description: 'Wheat flour, white, all-purpose, enriched, bleached',
    calories: 364,
    protein: 10.33,
    totalFat: 0.98,
    saturatedFat: 0.155,
    carbohydrates: 76.31,
    sugar: 0.27,
    fiber: 2.7,
    sodium: 2,
  },
  cornstarch: {
    fdcId: 169698,
    description: 'Cornstarch',
    calories: 381,
    protein: 0.26,
    totalFat: 0.05,
    saturatedFat: 0.009,
    carbohydrates: 91.27,
    sugar: 0,
    fiber: 0.9,
    sodium: 9,
  },
  granulated_sugar: {
    fdcId: 169655,
    description: 'Sugars, granulated',
    calories: 387,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 99.98,
    sugar: 99.80,
    fiber: 0,
    sodium: 1,
  },
  brown_sugar: {
    fdcId: 168833,
    description: 'Sugars, brown',
    calories: 380,
    protein: 0.12,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 98.09,
    sugar: 97.02,
    fiber: 0,
    sodium: 28,
  },
  powdered_sugar: {
    fdcId: 169656,
    description: 'Sugars, powdered',
    calories: 389,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 99.77,
    sugar: 97.81,
    fiber: 0,
    sodium: 2,
  },
  milk: {
    fdcId: 171265,
    description: 'Milk, whole, 3.25% milkfat',
    calories: 61,
    protein: 3.15,
    totalFat: 3.27,
    saturatedFat: 1.865,
    carbohydrates: 4.78,
    sugar: 5.05,
    fiber: 0,
    sodium: 43,
  },
  cream_cheese: {
    fdcId: 173418,
    description: 'Cheese, cream',
    calories: 342,
    protein: 5.93,
    totalFat: 34.24,
    saturatedFat: 19.29,
    carbohydrates: 5.52,
    sugar: 3.76,
    fiber: 0,
    sodium: 321,
  },
  eggs: {
    fdcId: 171287,
    description: 'Egg, whole, raw, fresh',
    calories: 143,
    protein: 12.56,
    totalFat: 9.51,
    saturatedFat: 3.126,
    carbohydrates: 0.72,
    sugar: 0.37,
    fiber: 0,
    sodium: 142,
  },
  yeast: {
    fdcId: 175043,
    description: "Leavening agents, yeast, baker's, active dry",
    calories: 325,
    protein: 40.44,
    totalFat: 7.61,
    saturatedFat: 0.98,
    carbohydrates: 41.22,
    sugar: 0,
    fiber: 26.9,
    sodium: 51,
  },
  cinnamon: {
    fdcId: 171320,
    description: 'Spices, cinnamon, ground',
    calories: 247,
    protein: 3.99,
    totalFat: 1.24,
    saturatedFat: 0.345,
    carbohydrates: 80.59,
    sugar: 2.17,
    fiber: 53.1,
    sodium: 10,
  },
  salt: {
    fdcId: 173468,
    description: 'Salt, table',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 38758,
  },
  vanilla: {
    fdcId: 173471,
    description: 'Vanilla extract',
    calories: 288,
    protein: 0.06,
    totalFat: 0.06,
    saturatedFat: 0.01,
    carbohydrates: 12.65,
    sugar: 12.65,
    fiber: 0,
    sodium: 9,
  },

  // ── Tartine Baguette ingredients ──

  ap_flour: {
    fdcId: 168894,
    description: 'Wheat flour, white, all-purpose, enriched, bleached',
    calories: 364,
    protein: 10.33,
    totalFat: 0.98,
    saturatedFat: 0.155,
    carbohydrates: 76.31,
    sugar: 0.27,
    fiber: 2.7,
    sodium: 2,
  },
  bread_flour: {
    fdcId: 168896,
    description: 'Wheat flour, white, bread, enriched',
    calories: 361,
    protein: 11.98,
    totalFat: 1.66,
    saturatedFat: 0.244,
    carbohydrates: 72.53,
    sugar: 0.27,
    fiber: 2.4,
    sodium: 2,
  },
  water: {
    fdcId: 173647,
    description: 'Beverages, water, tap, drinking',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 4,
  },
  starter: {
    fdcId: 0, // Derived: 100% hydration starter ≈ 50% AP flour + 50% water
    description: 'Sourdough starter, 100% hydration (derived from AP flour)',
    calories: 182,
    protein: 5.17,
    totalFat: 0.49,
    saturatedFat: 0.078,
    carbohydrates: 38.16,
    sugar: 0.14,
    fiber: 1.35,
    sodium: 3,
  },

  // ── CoCo Curry ingredients ──

  // Proxy: No USDA entry for Japanese curry roux blocks. Values from House Foods
  // Java Curry Medium Hot label (per 100g). FDC ID 0 = derived/label data.
  curry_roux: {
    fdcId: 0,
    description: 'House Foods Java Curry roux, Medium Hot (label data)',
    calories: 534,
    protein: 8.3,
    totalFat: 40.7,
    saturatedFat: 22.0,
    carbohydrates: 35.2,
    sugar: 1.0,
    fiber: 3.1,
    sodium: 5120, // 12.8g salt ÷ 2.5 = 5120mg sodium
  },
  curry_powder: {
    fdcId: 172155,
    description: 'Spices, curry powder',
    calories: 325,
    protein: 12.66,
    totalFat: 13.81,
    saturatedFat: 2.24,
    carbohydrates: 58.15,
    sugar: 2.76,
    fiber: 33.2,
    sodium: 52,
  },
  onions: {
    fdcId: 170000,
    description: 'Onions, raw',
    calories: 40,
    protein: 1.1,
    totalFat: 0.1,
    saturatedFat: 0.042,
    carbohydrates: 9.34,
    sugar: 4.24,
    fiber: 1.7,
    sodium: 4,
  },
  carrot: {
    fdcId: 170393,
    description: 'Carrots, raw',
    calories: 41,
    protein: 0.93,
    totalFat: 0.24,
    saturatedFat: 0.032,
    carbohydrates: 9.58,
    sugar: 4.74,
    fiber: 2.8,
    sodium: 69,
  },
  apple: {
    fdcId: 171688,
    description: 'Apples, raw, with skin',
    calories: 52,
    protein: 0.26,
    totalFat: 0.17,
    saturatedFat: 0.028,
    carbohydrates: 13.81,
    sugar: 10.39,
    fiber: 2.4,
    sodium: 1,
  },
  pork: {
    fdcId: 167849,
    description: 'Pork, fresh, shoulder (Boston butt), blade, separable lean and fat, raw',
    calories: 186,
    protein: 17.42,
    totalFat: 12.44,
    saturatedFat: 4.36,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 61,
  },
  beef_broth: {
    fdcId: 174256,
    description: 'Soup, beef broth or bouillon, canned, ready-to-serve',
    calories: 7,
    protein: 1.14,
    totalFat: 0.22,
    saturatedFat: 0.11,
    carbohydrates: 0.04,
    sugar: 0,
    fiber: 0,
    sodium: 372,
  },
  oil: {
    fdcId: 171411,
    description: 'Oil, soybean, salad or cooking',
    calories: 884,
    protein: 0,
    totalFat: 100,
    saturatedFat: 15.65,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 0,
  },
  // Proxy: No USDA entry for mango chutney. Using branded label data (Sharwood's).
  // Chutney is primarily sugar + mango + spices with negligible fat/protein.
  mango_chutney: {
    fdcId: 0,
    description: 'Mango chutney (branded label proxy: Sharwood\'s)',
    calories: 250,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 60,
    sugar: 50,
    fiber: 0,
    sodium: 1400,
  },
  worcestershire: {
    fdcId: 171610,
    description: 'Worcestershire sauce',
    calories: 78,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 19.46,
    sugar: 10.0,
    fiber: 0,
    sodium: 980,
  },
  // Proxy: No USDA entry for Japanese chuno sauce. Bull-Dog Fruit & Vegetable
  // (tonkatsu-style) sauce used as proxy — similar formulation of fruits,
  // vegetables, vinegar, and sugar. Values from product label via Open Food Facts.
  chuno_sauce: {
    fdcId: 0,
    description: 'Bull-Dog Fruit & Vegetable sauce (tonkatsu-style, label proxy)',
    calories: 150,
    protein: 0.6,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 36.1,
    sugar: 35.6,
    fiber: 0,
    sodium: 5605,
  },
  soy_sauce: {
    fdcId: 174277,
    description: 'Soy sauce made from soy and wheat (shoyu)',
    calories: 53,
    protein: 8.14,
    totalFat: 0.57,
    saturatedFat: 0.073,
    carbohydrates: 4.93,
    sugar: 0.4,
    fiber: 0.8,
    sodium: 5493,
  },
  miso: {
    fdcId: 172442,
    description: 'Miso',
    calories: 199,
    protein: 11.69,
    totalFat: 6.01,
    saturatedFat: 1.02,
    carbohydrates: 26.47,
    sugar: 6.2,
    fiber: 5.4,
    sodium: 3728,
  },
  instant_coffee: {
    fdcId: 171912,
    description: 'Beverages, coffee, instant, regular, powder',
    calories: 353,
    protein: 12.2,
    totalFat: 0.5,
    saturatedFat: 0.26,
    carbohydrates: 75.4,
    sugar: 0,
    fiber: 0,
    sodium: 37,
  },
  chocolate: {
    fdcId: 170273,
    description: 'Chocolate, dark, 70-85% cacao solids',
    calories: 598,
    protein: 7.79,
    totalFat: 42.63,
    saturatedFat: 24.49,
    carbohydrates: 45.9,
    sugar: 23.99,
    fiber: 10.9,
    sodium: 20,
  },
  peanut_butter: {
    fdcId: 172470,
    description: 'Peanut butter, smooth style, without salt',
    calories: 588,
    protein: 25.09,
    totalFat: 50.39,
    saturatedFat: 10.33,
    carbohydrates: 19.56,
    sugar: 6.16,
    fiber: 6.0,
    sodium: 17,
  },
  rice_vinegar: {
    fdcId: 173568,
    description: 'Vinegar, rice',
    calories: 18,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0.04,
    sugar: 0.04,
    fiber: 0,
    sodium: 2,
  },
  white_pepper: {
    fdcId: 170931,
    description: 'Spices, pepper, white',
    calories: 296,
    protein: 10.4,
    totalFat: 2.12,
    saturatedFat: 0.63,
    carbohydrates: 68.61,
    sugar: 0,
    fiber: 26.2,
    sodium: 5,
  },
  honey: {
    fdcId: 169640,
    description: 'Honey',
    calories: 304,
    protein: 0.3,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 82.4,
    sugar: 82.12,
    fiber: 0.2,
    sodium: 4,
  },
  rice: {
    fdcId: 169757,
    description: 'Rice, white, short-grain, raw, unenriched',
    calories: 358,
    protein: 6.5,
    totalFat: 0.52,
    saturatedFat: 0.15,
    carbohydrates: 79.15,
    sugar: 0,
    fiber: 2.8,
    sodium: 1,
  },
}
