/**
 * USDA FoodData Central — SR Legacy nutritional data per 100g.
 * Source: https://fdc.nal.usda.gov/
 *
 * Each entry keyed by ingredient ID from recipe JSON.
 * All nutrient values are per 100g of the ingredient.
 */

export interface NutrientsPer100g {
  fdcId: number
  description: string
  calories: number       // kcal
  protein: number        // g
  totalFat: number       // g
  saturatedFat: number   // g
  carbohydrates: number  // g
  sugar: number          // g
  fiber: number          // g
  sodium: number         // mg
}

/** Weight conversion for unit: "whole" ingredients */
export const WHOLE_UNIT_GRAMS: Record<string, number> = {
  eggs: 50, // 1 large egg without shell ≈ 50g
}

export const USDA_NUTRIENTS: Record<string, NutrientsPer100g> = {
  butter: {
    fdcId: 173430,
    description: 'Butter, without salt',
    calories: 717,
    protein: 0.85,
    totalFat: 81.11,
    saturatedFat: 51.37,
    carbohydrates: 0.06,
    sugar: 0.06,
    fiber: 0,
    sodium: 11,
  },
  flour: {
    fdcId: 168894,
    description: 'Wheat flour, white, all-purpose, enriched, bleached',
    calories: 364,
    protein: 10.33,
    totalFat: 0.98,
    saturatedFat: 0.155,
    carbohydrates: 76.31,
    sugar: 0.27,
    fiber: 2.7,
    sodium: 2,
  },
  cornstarch: {
    fdcId: 169698,
    description: 'Cornstarch',
    calories: 381,
    protein: 0.26,
    totalFat: 0.05,
    saturatedFat: 0.009,
    carbohydrates: 91.27,
    sugar: 0,
    fiber: 0.9,
    sodium: 9,
  },
  granulated_sugar: {
    fdcId: 169655,
    description: 'Sugars, granulated',
    calories: 387,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 99.98,
    sugar: 99.80,
    fiber: 0,
    sodium: 1,
  },
  brown_sugar: {
    fdcId: 168833,
    description: 'Sugars, brown',
    calories: 380,
    protein: 0.12,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 98.09,
    sugar: 97.02,
    fiber: 0,
    sodium: 28,
  },
  powdered_sugar: {
    fdcId: 169656,
    description: 'Sugars, powdered',
    calories: 389,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 99.77,
    sugar: 97.81,
    fiber: 0,
    sodium: 2,
  },
  milk: {
    fdcId: 171265,
    description: 'Milk, whole, 3.25% milkfat',
    calories: 61,
    protein: 3.15,
    totalFat: 3.27,
    saturatedFat: 1.865,
    carbohydrates: 4.78,
    sugar: 5.05,
    fiber: 0,
    sodium: 43,
  },
  cream_cheese: {
    fdcId: 173418,
    description: 'Cheese, cream',
    calories: 342,
    protein: 5.93,
    totalFat: 34.24,
    saturatedFat: 19.29,
    carbohydrates: 5.52,
    sugar: 3.76,
    fiber: 0,
    sodium: 321,
  },
  eggs: {
    fdcId: 171287,
    description: 'Egg, whole, raw, fresh',
    calories: 143,
    protein: 12.56,
    totalFat: 9.51,
    saturatedFat: 3.126,
    carbohydrates: 0.72,
    sugar: 0.37,
    fiber: 0,
    sodium: 142,
  },
  yeast: {
    fdcId: 175043,
    description: "Leavening agents, yeast, baker's, active dry",
    calories: 325,
    protein: 40.44,
    totalFat: 7.61,
    saturatedFat: 0.98,
    carbohydrates: 41.22,
    sugar: 0,
    fiber: 26.9,
    sodium: 51,
  },
  cinnamon: {
    fdcId: 171320,
    description: 'Spices, cinnamon, ground',
    calories: 247,
    protein: 3.99,
    totalFat: 1.24,
    saturatedFat: 0.345,
    carbohydrates: 80.59,
    sugar: 2.17,
    fiber: 53.1,
    sodium: 10,
  },
  salt: {
    fdcId: 173468,
    description: 'Salt, table',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 38758,
  },
  vanilla: {
    fdcId: 173471,
    description: 'Vanilla extract',
    calories: 288,
    protein: 0.06,
    totalFat: 0.06,
    saturatedFat: 0.01,
    carbohydrates: 12.65,
    sugar: 12.65,
    fiber: 0,
    sodium: 9,
  },

  baking_powder: {
    fdcId: 171015,
    description: 'Leavening agents, baking powder, double-acting, sodium aluminum sulfate',
    calories: 53,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 27.7,
    sugar: 0,
    fiber: 0.2,
    sodium: 10600,
  },
  cloves: {
    fdcId: 171321,
    description: 'Spices, cloves, ground',
    calories: 274,
    protein: 5.97,
    totalFat: 13.0,
    saturatedFat: 3.952,
    carbohydrates: 65.53,
    sugar: 2.38,
    fiber: 33.9,
    sodium: 277,
  },

  // ── Tartine Baguette ingredients ──

  ap_flour: {
    fdcId: 168894,
    description: 'Wheat flour, white, all-purpose, enriched, bleached',
    calories: 364,
    protein: 10.33,
    totalFat: 0.98,
    saturatedFat: 0.155,
    carbohydrates: 76.31,
    sugar: 0.27,
    fiber: 2.7,
    sodium: 2,
  },
  bread_flour: {
    fdcId: 168896,
    description: 'Wheat flour, white, bread, enriched',
    calories: 361,
    protein: 11.98,
    totalFat: 1.66,
    saturatedFat: 0.244,
    carbohydrates: 72.53,
    sugar: 0.27,
    fiber: 2.4,
    sodium: 2,
  },
  water: {
    fdcId: 173647,
    description: 'Beverages, water, tap, drinking',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 4,
  },
  starter: {
    fdcId: 0, // Derived: 100% hydration starter ≈ 50% AP flour + 50% water
    description: 'Sourdough starter, 100% hydration (derived from AP flour)',
    calories: 182,
    protein: 5.17,
    totalFat: 0.49,
    saturatedFat: 0.078,
    carbohydrates: 38.16,
    sugar: 0.14,
    fiber: 1.35,
    sodium: 3,
  },

  // ── CoCo Curry ingredients ──

  // Proxy: No USDA entry for Japanese curry roux blocks. Values from House Foods
  // Java Curry Medium Hot label (per 100g). FDC ID 0 = derived/label data.
  curry_roux: {
    fdcId: 0,
    description: 'House Foods Java Curry roux, Medium Hot (label data)',
    calories: 534,
    protein: 8.3,
    totalFat: 40.7,
    saturatedFat: 22.0,
    carbohydrates: 35.2,
    sugar: 1.0,
    fiber: 3.1,
    sodium: 5120, // 12.8g salt ÷ 2.5 = 5120mg sodium
  },
  curry_powder: {
    fdcId: 172155,
    description: 'Spices, curry powder',
    calories: 325,
    protein: 12.66,
    totalFat: 13.81,
    saturatedFat: 2.24,
    carbohydrates: 58.15,
    sugar: 2.76,
    fiber: 33.2,
    sodium: 52,
  },
  onions: {
    fdcId: 170000,
    description: 'Onions, raw',
    calories: 40,
    protein: 1.1,
    totalFat: 0.1,
    saturatedFat: 0.042,
    carbohydrates: 9.34,
    sugar: 4.24,
    fiber: 1.7,
    sodium: 4,
  },
  carrot: {
    fdcId: 170393,
    description: 'Carrots, raw',
    calories: 41,
    protein: 0.93,
    totalFat: 0.24,
    saturatedFat: 0.032,
    carbohydrates: 9.58,
    sugar: 4.74,
    fiber: 2.8,
    sodium: 69,
  },
  apple: {
    fdcId: 171688,
    description: 'Apples, raw, with skin',
    calories: 52,
    protein: 0.26,
    totalFat: 0.17,
    saturatedFat: 0.028,
    carbohydrates: 13.81,
    sugar: 10.39,
    fiber: 2.4,
    sodium: 1,
  },
  pork: {
    fdcId: 167849,
    description: 'Pork, fresh, shoulder (Boston butt), blade, separable lean and fat, raw',
    calories: 186,
    protein: 17.42,
    totalFat: 12.44,
    saturatedFat: 4.36,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 61,
  },
  beef_broth: {
    fdcId: 174256,
    description: 'Soup, beef broth or bouillon, canned, ready-to-serve',
    calories: 7,
    protein: 1.14,
    totalFat: 0.22,
    saturatedFat: 0.11,
    carbohydrates: 0.04,
    sugar: 0,
    fiber: 0,
    sodium: 372,
  },
  oil: {
    fdcId: 171411,
    description: 'Oil, soybean, salad or cooking',
    calories: 884,
    protein: 0,
    totalFat: 100,
    saturatedFat: 15.65,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 0,
  },
  // Proxy: No USDA entry for mango chutney. Using branded label data (Sharwood's).
  // Chutney is primarily sugar + mango + spices with negligible fat/protein.
  mango_chutney: {
    fdcId: 0,
    description: 'Mango chutney (branded label proxy: Sharwood\'s)',
    calories: 250,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 60,
    sugar: 50,
    fiber: 0,
    sodium: 1400,
  },
  worcestershire: {
    fdcId: 171610,
    description: 'Worcestershire sauce',
    calories: 78,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 19.46,
    sugar: 10.0,
    fiber: 0,
    sodium: 980,
  },
  // Proxy: No USDA entry for Japanese chuno sauce. Bull-Dog Fruit & Vegetable
  // (tonkatsu-style) sauce used as proxy — similar formulation of fruits,
  // vegetables, vinegar, and sugar. Values from product label via Open Food Facts.
  chuno_sauce: {
    fdcId: 0,
    description: 'Bull-Dog Fruit & Vegetable sauce (tonkatsu-style, label proxy)',
    calories: 150,
    protein: 0.6,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 36.1,
    sugar: 35.6,
    fiber: 0,
    sodium: 5605,
  },
  soy_sauce: {
    fdcId: 174277,
    description: 'Soy sauce made from soy and wheat (shoyu)',
    calories: 53,
    protein: 8.14,
    totalFat: 0.57,
    saturatedFat: 0.073,
    carbohydrates: 4.93,
    sugar: 0.4,
    fiber: 0.8,
    sodium: 5493,
  },
  miso: {
    fdcId: 172442,
    description: 'Miso',
    calories: 199,
    protein: 11.69,
    totalFat: 6.01,
    saturatedFat: 1.02,
    carbohydrates: 26.47,
    sugar: 6.2,
    fiber: 5.4,
    sodium: 3728,
  },
  instant_coffee: {
    fdcId: 171912,
    description: 'Beverages, coffee, instant, regular, powder',
    calories: 353,
    protein: 12.2,
    totalFat: 0.5,
    saturatedFat: 0.26,
    carbohydrates: 75.4,
    sugar: 0,
    fiber: 0,
    sodium: 37,
  },
  chocolate: {
    fdcId: 170273,
    description: 'Chocolate, dark, 70-85% cacao solids',
    calories: 598,
    protein: 7.79,
    totalFat: 42.63,
    saturatedFat: 24.49,
    carbohydrates: 45.9,
    sugar: 23.99,
    fiber: 10.9,
    sodium: 20,
  },
  peanut_butter: {
    fdcId: 172470,
    description: 'Peanut butter, smooth style, without salt',
    calories: 588,
    protein: 25.09,
    totalFat: 50.39,
    saturatedFat: 10.33,
    carbohydrates: 19.56,
    sugar: 6.16,
    fiber: 6.0,
    sodium: 17,
  },
  rice_vinegar: {
    fdcId: 173568,
    description: 'Vinegar, rice',
    calories: 18,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0.04,
    sugar: 0.04,
    fiber: 0,
    sodium: 2,
  },
  white_pepper: {
    fdcId: 170931,
    description: 'Spices, pepper, white',
    calories: 296,
    protein: 10.4,
    totalFat: 2.12,
    saturatedFat: 0.63,
    carbohydrates: 68.61,
    sugar: 0,
    fiber: 26.2,
    sodium: 5,
  },
  honey: {
    fdcId: 169640,
    description: 'Honey',
    calories: 304,
    protein: 0.3,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 82.4,
    sugar: 82.12,
    fiber: 0.2,
    sodium: 4,
  },
  rice: {
    fdcId: 169757,
    description: 'Rice, white, short-grain, raw, unenriched',
    calories: 358,
    protein: 6.5,
    totalFat: 0.52,
    saturatedFat: 0.15,
    carbohydrates: 79.15,
    sugar: 0,
    fiber: 2.8,
    sodium: 1,
  },

  // ── Thai Tea Boba ingredients ──

  // Proxy: ChaTraMue Thai tea mix is dried ceylon tea leaves + food coloring,
  // steeped and strained out. Brewed tea liquid contributes ~1 kcal/100ml.
  // Using USDA "Beverages, tea, brewed" as proxy for what actually enters the drink.
  // FDC ID 0 = derived/proxy data.
  thai_tea_mix: {
    fdcId: 0,
    description: 'ChaTraMue Thai tea mix (brewed and strained; proxy: brewed tea)',
    calories: 1,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0.3,
    sugar: 0,
    fiber: 0,
    sodium: 3,
  },
  tapioca_pearls: {
    fdcId: 169717,
    description: 'Tapioca, pearl, dry',
    calories: 358,
    protein: 0.19,
    totalFat: 0.02,
    saturatedFat: 0.005,
    carbohydrates: 88.69,
    sugar: 3.35,
    fiber: 0.9,
    sodium: 1,
  },
  condensed_milk: {
    fdcId: 171275,
    description: 'Milk, canned, condensed, sweetened',
    calories: 321,
    protein: 7.91,
    totalFat: 8.7,
    saturatedFat: 5.49,
    carbohydrates: 54.4,
    sugar: 54.4,
    fiber: 0,
    sodium: 127,
  },
  evaporated_milk: {
    fdcId: 172194,
    description: 'Milk, canned, evaporated, with added vitamin A',
    calories: 134,
    protein: 6.81,
    totalFat: 7.56,
    saturatedFat: 4.59,
    carbohydrates: 10.04,
    sugar: 10.04,
    fiber: 0,
    sodium: 106,
  },
  ice: {
    fdcId: 173647,
    description: 'Ice (frozen water; same as tap water)',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 4,
  },

  // ── Ichiran Ramen + Tomita Tsukemen ingredients ──

  // --- Bones & Collagen Sources (EXTRACTION ONLY) ---
  // Tonkotsu broth: bones are simmered 12h+ (or pressure-cooked 4h) then strained.
  // Values represent estimated nutrient extraction into liquid, NOT raw bone nutrition.
  // Conservative model: ~15-25% of raw collagen/fat transfers to broth.
  // Research basis: tonkotsu broth ≈ 40-60 kcal/100ml; back-calculated to per-100g-bones-used.

  pork_femur_bones: {
    fdcId: 0,
    description: 'Pork femur bones — tonkotsu extraction estimate (solids discarded after 12h cook)',
    calories: 15,
    protein: 3.0,
    totalFat: 0.5,
    saturatedFat: 0.15,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 15,
  },
  pork_trotters: {
    fdcId: 0,
    description: 'Pork trotters — tonkotsu extraction estimate (very high gelatin; solids discarded)',
    calories: 25,
    protein: 5.0,
    totalFat: 1.0,
    saturatedFat: 0.4,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 20,
  },
  pork_neck_bones: {
    fdcId: 0,
    description: 'Pork neck bones — tonkotsu extraction estimate (solids discarded)',
    calories: 15,
    protein: 3.0,
    totalFat: 0.5,
    saturatedFat: 0.15,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 15,
  },
  pork_skin: {
    fdcId: 0,
    description: 'Pork skin — tonkotsu extraction estimate (very high gelatin; solids discarded)',
    calories: 30,
    protein: 6.0,
    totalFat: 1.0,
    saturatedFat: 0.3,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 15,
  },
  pork_bones: {
    fdcId: 0,
    description: 'Pork bones (generic) — tonkotsu extraction estimate (solids discarded)',
    calories: 15,
    protein: 3.0,
    totalFat: 0.5,
    saturatedFat: 0.15,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 15,
  },
  chicken_feet: {
    fdcId: 0,
    description: 'Chicken feet — broth extraction estimate (70% collagen; solids discarded)',
    calories: 25,
    protein: 5.0,
    totalFat: 1.0,
    saturatedFat: 0.3,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 20,
  },
  chicken_backs: {
    fdcId: 0,
    description: 'Chicken backs — broth extraction estimate (solids discarded)',
    calories: 20,
    protein: 3.5,
    totalFat: 1.0,
    saturatedFat: 0.3,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 18,
  },

  // --- Consumed Meats ---

  pork_shoulder: {
    fdcId: 167849,
    description: 'Pork, fresh, shoulder (Boston butt), blade, separable lean and fat, raw',
    calories: 186,
    protein: 17.42,
    totalFat: 12.44,
    saturatedFat: 4.36,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 61,
  },
  pork_back_fat: {
    fdcId: 167884,
    description: 'Pork, fresh, backfat, raw (rendered into aroma oil — fully consumed)',
    calories: 812,
    protein: 2.92,
    totalFat: 88.69,
    saturatedFat: 32.24,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 11,
  },
  pork_belly: {
    fdcId: 167803,
    description: 'Pork, fresh, belly, raw (cooked in broth then eaten as chashu — fully consumed)',
    calories: 518,
    protein: 9.34,
    totalFat: 53.01,
    saturatedFat: 19.33,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 32,
  },

  // --- Japanese Seasonings ---

  sake: {
    fdcId: 174857,
    description: 'Alcoholic beverage, rice (sake)',
    calories: 134,
    protein: 0.5,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 5.0,
    sugar: 0,
    fiber: 0,
    sodium: 2,
  },
  mirin: {
    fdcId: 0,
    description: 'Hon mirin (Takara label data; 14% alcohol, sweet rice wine)',
    calories: 241,
    protein: 0.3,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 45.8,
    sugar: 43.2,
    fiber: 0,
    sodium: 3,
  },
  sugar: {
    fdcId: 169655,
    description: 'Sugars, granulated',
    calories: 387,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 99.98,
    sugar: 99.80,
    fiber: 0,
    sodium: 1,
  },
  msg: {
    fdcId: 0,
    description: 'Monosodium glutamate (flavor enhancer; negligible calories, significant sodium)',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 12280,
  },
  ribotide: {
    fdcId: 0,
    description: 'Ribotide IMP+GMP nucleotide blend (flavor enhancer; negligible calories)',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 3000,
  },

  // --- Aromatics ---

  garlic: {
    fdcId: 169230,
    description: 'Garlic, raw',
    calories: 149,
    protein: 6.36,
    totalFat: 0.5,
    saturatedFat: 0.089,
    carbohydrates: 33.06,
    sugar: 1.0,
    fiber: 2.1,
    sodium: 17,
  },
  ginger: {
    fdcId: 169231,
    description: 'Ginger root, raw',
    calories: 80,
    protein: 1.82,
    totalFat: 0.75,
    saturatedFat: 0.203,
    carbohydrates: 17.77,
    sugar: 1.7,
    fiber: 2.0,
    sodium: 13,
  },
  onion: {
    fdcId: 170000,
    description: 'Onions, raw',
    calories: 40,
    protein: 1.1,
    totalFat: 0.1,
    saturatedFat: 0.042,
    carbohydrates: 9.34,
    sugar: 4.24,
    fiber: 1.7,
    sodium: 4,
  },
  scallion_whites: {
    fdcId: 170497,
    description: 'Onions, spring or scallions, raw (white parts only)',
    calories: 32,
    protein: 1.83,
    totalFat: 0.19,
    saturatedFat: 0.032,
    carbohydrates: 7.34,
    sugar: 2.33,
    fiber: 2.6,
    sodium: 16,
  },
  green_onion: {
    fdcId: 170497,
    description: 'Onions, spring or scallions (includes tops and bulb), raw',
    calories: 32,
    protein: 1.83,
    totalFat: 0.19,
    saturatedFat: 0.032,
    carbohydrates: 7.34,
    sugar: 2.33,
    fiber: 2.6,
    sodium: 16,
  },

  // --- Dried Sea Products ---
  // Values represent weighted averages based on breakdown proportions:
  // portions steeped-and-strained (25% extraction) vs portions ground into gyofun (100% consumed).
  // Derivation documented per entry. Ichiran uses extraction-only (all strained);
  // tsukemen weighted values used as canonical — overcounting for ichiran is <1 kcal/serving.

  kombu: {
    fdcId: 0,
    description: 'Kombu, dried kelp — dashi extraction estimate (~25% nutrient transfer; soaked/steeped, solids removed)',
    calories: 36,
    protein: 2.0,
    totalFat: 0.4,
    saturatedFat: 0.1,
    carbohydrates: 2.4,
    sugar: 0.2,
    fiber: 0,
    sodium: 600,
  },
  dried_shiitake: {
    fdcId: 172410,
    description: 'Mushrooms, shiitake, dried (full values — only 3g used, impact negligible)',
    calories: 296,
    protein: 9.58,
    totalFat: 0.99,
    saturatedFat: 0.225,
    carbohydrates: 75.37,
    sugar: 2.21,
    fiber: 11.5,
    sodium: 13,
  },
  katsuobushi: {
    fdcId: 0,
    description: 'Katsuobushi, dried bonito — weighted: 78% steeped/strained (25% extraction) + 22% gyofun (100%)',
    calories: 140,
    protein: 31.8,
    totalFat: 1.2,
    saturatedFat: 0.33,
    carbohydrates: 0.3,
    sugar: 0,
    fiber: 0,
    sodium: 54,
  },
  niboshi: {
    fdcId: 0,
    description: 'Niboshi, dried sardines — weighted: 89% steeped/strained (25% extraction) + 11% gyofun (100%)',
    calories: 110,
    protein: 21.3,
    totalFat: 2.0,
    saturatedFat: 0.5,
    carbohydrates: 0.1,
    sugar: 0,
    fiber: 0,
    sodium: 499,
  },
  sababushi: {
    fdcId: 0,
    description: 'Sababushi, dried mackerel — weighted: 68% steeped/strained (25% extraction) + 32% gyofun (100%)',
    calories: 162,
    protein: 31.6,
    totalFat: 3.9,
    saturatedFat: 1.1,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 700,
  },
  dried_flounder_powder: {
    fdcId: 0,
    description: 'Dried flounder powder — 100% consumed as gyofun (ground powder added directly to broth)',
    calories: 330,
    protein: 70.0,
    totalFat: 3.5,
    saturatedFat: 1.0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 400,
  },

  // --- Chili & Spices ---

  ichimi_togarashi: {
    fdcId: 170925,
    description: 'Japanese chili powder (proxy: Spices, pepper, red or cayenne)',
    calories: 318,
    protein: 12.01,
    totalFat: 17.27,
    saturatedFat: 3.26,
    carbohydrates: 56.63,
    sugar: 10.34,
    fiber: 27.2,
    sodium: 30,
  },
  gochugaru: {
    fdcId: 0,
    description: 'Korean red pepper flakes (gochugaru) — label data composite',
    calories: 290,
    protein: 11.0,
    totalFat: 14.0,
    saturatedFat: 2.5,
    carbohydrates: 50.0,
    sugar: 10.0,
    fiber: 28.0,
    sodium: 20,
  },
  cayenne: {
    fdcId: 170925,
    description: 'Spices, pepper, red or cayenne',
    calories: 318,
    protein: 12.01,
    totalFat: 17.27,
    saturatedFat: 3.26,
    carbohydrates: 56.63,
    sugar: 10.34,
    fiber: 27.2,
    sodium: 30,
  },
  black_pepper: {
    fdcId: 170929,
    description: 'Spices, pepper, black',
    calories: 251,
    protein: 10.39,
    totalFat: 3.26,
    saturatedFat: 1.39,
    carbohydrates: 63.95,
    sugar: 0.64,
    fiber: 25.3,
    sodium: 20,
  },

  // --- Red Sauce / Paste Ingredients ---

  garlic_paste_red: {
    fdcId: 169230,
    description: 'Garlic paste for red sauce (same nutrition as raw garlic)',
    calories: 149,
    protein: 6.36,
    totalFat: 0.5,
    saturatedFat: 0.089,
    carbohydrates: 33.06,
    sugar: 1.0,
    fiber: 2.1,
    sodium: 17,
  },
  gochujang: {
    fdcId: 0,
    description: 'Gochujang, fermented chili paste (CJ Haechandle label data)',
    calories: 175,
    protein: 4.5,
    totalFat: 2.5,
    saturatedFat: 0.4,
    carbohydrates: 34.0,
    sugar: 19.0,
    fiber: 4.0,
    sodium: 2280,
  },
  sesame_oil: {
    fdcId: 171028,
    description: 'Oil, sesame, salad or cooking',
    calories: 884,
    protein: 0,
    totalFat: 100,
    saturatedFat: 14.2,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 0,
  },
  neutral_oil: {
    fdcId: 171411,
    description: 'Neutral oil (alias: soybean/canola oil)',
    calories: 884,
    protein: 0,
    totalFat: 100,
    saturatedFat: 15.65,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 0,
  },

  // --- Noodle Ingredients ---

  vital_wheat_gluten: {
    fdcId: 175369,
    description: 'Vital wheat gluten',
    calories: 370,
    protein: 75.16,
    totalFat: 1.85,
    saturatedFat: 0.26,
    carbohydrates: 13.79,
    sugar: 0.85,
    fiber: 0.6,
    sodium: 29,
  },
  whole_wheat_flour: {
    fdcId: 169761,
    description: 'Wheat flour, whole-grain',
    calories: 340,
    protein: 13.21,
    totalFat: 2.5,
    saturatedFat: 0.43,
    carbohydrates: 71.97,
    sugar: 0.41,
    fiber: 10.7,
    sodium: 2,
  },
  kansui: {
    fdcId: 0,
    description: 'Kansui alkaline salt (Na₂CO₃ + K₂CO₃) — negligible calories; sodium from Na₂CO₃',
    calories: 0,
    protein: 0,
    totalFat: 0,
    saturatedFat: 0,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 27000,
  },

  // --- Water (all zero-calorie, various recipe uses) ---

  cold_water_noodles: {
    fdcId: 173647, description: 'Water (for noodle dough)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  water_aroma_oil: {
    fdcId: 173647, description: 'Water (splash for aroma oil rendering)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  water_tare_dashi: {
    fdcId: 173647, description: 'Water (for tare dashi)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  water_ajitama: {
    fdcId: 173647, description: 'Water (for ajitama marinade)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  noodle_water: {
    fdcId: 173647, description: 'Water (for noodle dough)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  ajitama_water: {
    fdcId: 173647, description: 'Water (for ajitama marinade)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  chashu_water: {
    fdcId: 173647, description: 'Water (for chashu marinade)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  broth_water: {
    fdcId: 173647, description: 'Water (for broth)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  dashi_water: {
    fdcId: 173647, description: 'Water (for fish dashi)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 4,
  },
  noodle_salt: {
    fdcId: 173468, description: 'Salt, table (for noodle dough)',
    calories: 0, protein: 0, totalFat: 0, saturatedFat: 0,
    carbohydrates: 0, sugar: 0, fiber: 0, sodium: 38758,
  },

  // --- Toppings & Garnishes ---

  nori: {
    fdcId: 0,
    description: 'Nori, dried seaweed sheets (Japanese food composition data)',
    calories: 190,
    protein: 30.7,
    totalFat: 0.3,
    saturatedFat: 0.1,
    carbohydrates: 44.3,
    sugar: 0.5,
    fiber: 36.0,
    sodium: 530,
  },
  menma: {
    fdcId: 0,
    description: 'Menma, seasoned bamboo shoots (branded label proxy)',
    calories: 30,
    protein: 2.0,
    totalFat: 0.5,
    saturatedFat: 0.1,
    carbohydrates: 4.0,
    sugar: 3.0,
    fiber: 1.5,
    sodium: 700,
  },

  // ── NY-Style Pizza (PF-80) ──

  olive_oil: {
    fdcId: 171413,
    description: 'Oil, olive, salad or cooking',
    calories: 884,
    protein: 0,
    totalFat: 100,
    saturatedFat: 13.81,
    carbohydrates: 0,
    sugar: 0,
    fiber: 0,
    sodium: 2,
  },
  instant_yeast: {
    fdcId: 175043,
    description: "Leavening agents, yeast, baker's, instant dry",
    calories: 325,
    protein: 40.44,
    totalFat: 7.61,
    saturatedFat: 0.98,
    carbohydrates: 41.22,
    sugar: 0,
    fiber: 26.9,
    sodium: 51,
  },
  cornmeal: {
    fdcId: 168876,
    description: 'Cornmeal, yellow, whole-grain',
    calories: 362,
    protein: 8.12,
    totalFat: 3.59,
    saturatedFat: 0.51,
    carbohydrates: 76.89,
    sugar: 1.61,
    fiber: 7.3,
    sodium: 7,
  },
  mozzarella: {
    fdcId: 170892,
    description: 'Cheese, mozzarella, low moisture, part skim',
    calories: 302,
    protein: 25.13,
    totalFat: 20.03,
    saturatedFat: 11.53,
    carbohydrates: 3.52,
    sugar: 1.01,
    fiber: 0,
    sodium: 627,
  },
  pepperoni: {
    fdcId: 174580,
    description: 'Pepperoni, pork, beef',
    calories: 494,
    protein: 22.46,
    totalFat: 43.88,
    saturatedFat: 17.12,
    carbohydrates: 2.79,
    sugar: 1.19,
    fiber: 0,
    sodium: 1761,
  },
  san_marzano_sauce: {
    fdcId: 170506,
    description: 'Tomato sauce, canned (proxy for crushed San Marzano)',
    calories: 29,
    protein: 1.32,
    totalFat: 0.21,
    saturatedFat: 0.028,
    carbohydrates: 5.82,
    sugar: 3.56,
    fiber: 1.5,
    sodium: 254,
  },
}
